language: crystal
dist: xenial
crystal:
  - latest
  - nightly

services:
  - docker

before_install:
  - docker pull consul:1.6.2
  - docker run -d -p 8500:8500 consul:1.6.2

script:
  - crystal spec
  - crystal tool format --check
