language: crystal
crystal:
  - latest

services:
  - docker

before_install:
  - docker pull consul:1.5.1
  - docker run -d -p 8500:8500 consul:1.5.1

script:
  - crystal spec
  - crystal tool format --check
